### ISSUE TITLE
Not working in .NET core 3.1

### ISSUE THREAD

**Issue by prinkpan** [Vereyon/FlashMessage#21]
I am facing exactly the same issue which is mentioned in #16 even after using version 2.0.0. I even tried the solution given there, by installing Newtonsoft, but that did not work either.

Flash message works when using `return View("Index")` and doesn't work while using `return RedirectToAction("Index")`

**Comment by cakkermans** [comment]
Hi @prinkpan, to check; for version 2.0.0, Netwontsoft.JSON is no longer required. Based on the problems you describe, I suspect the issue is in the `ITempDataProvider` being used.

I am assuming you are correctly adding the FlashMessage services in your startup code using `services.AddFlashMessage()`. This will attempt to also add the cooking based temp data provider. Are you by any chance using a different `ITempDataProvider`?

**Comment by prinkpan** [comment]
Thank you for your comment @cakkermans. Yes, I have correctly added FlashMessage to services using `services.AddFlashMessage()`. I am not using any different `ITempDataProvider`. Since the project was crucial, I am continuing without FlashMessage as of now. If you need any code for debugging, I will be happy to provide when I get a chance.

**Comment by cakkermans** [comment]
Hi @prinkpan, okay, that is to bad.

Something which might be worth while to look at is the code in your Startup.cs class. If it is not huge, would it be possible to supply me with that?

In addition, could you check using the browser network debugger if there is a cooking being set called ".AspNetCore.Mvc.CookieTempDataProvider", some something like it?

**Comment by cakkermans** [comment]
Closing this issue due to a lack of feedback and reproductions.
