### ISSUE TITLE
w3c validator

### ISSUE THREAD

**Issue by sptremblay** [Vereyon/FlashMessage#24]
When adding <flash> tag to my layout page
`<div class="col-10 offset-1">
        <flash dismissable="false"/>
    </div>` 
the w3c validator raise an error regarding the html 

 Element flash not allowed as child of element div in this context. (Suppressing further errors from this subtree.)

**Comment by cakkermans** [comment]
Hi @sptremblay, this is most likely because your <flash> tag is not being processed by ASP.NET. See the section in the documentation on the tag helper.

The validator is correct; <flash> is not a valid HTML tag. ASP.NET will however translate this tag into valid HTML markup displaying the flash messages.

I am closing this issue for now, as this seems to be a user issue.
