### ISSUE TITLE
Messages get lost

### ISSUE THREAD

**Issue by hypervtechnics** [Vereyon/FlashMessage#8]
Not sure if this is an issue or misusage.

Situation I am having 2 two controllers:
- Home
   - Index
- User
   - Index
   - Delete

When the user passes an invalid parameter to User.Delete i do a warning flashmessage and then he is redirected (RedirectToAction) to User.Index and when is not allowed to see User.Index as well i do a danger flashmessage and he is redirected (again RedirectToAction) to Home.Index where he is supposed to see **two** messages. But he only sees the danger one. When I comment out the danger message the warning message gets shown. Is the queue cleared somewhere in between or am I doint something wrong I didn't notice yet?

Hope you can help me.

**Comment by bernhardkircher** [comment]
@hypervtechnics Maybe this is useful for you. I had the same issue - I do not know what .NETversion etc you are running. 
I am running a .NET Core 2.1 web application. I had the same issue, that after a redirect, messages have not been shown to users (well, actually, to some it was shown...).
The problem in my case was unrelated to FlashMessage. When I created the new project, there is the following code, which handles CookiePolicy:

`services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;                
            });`

Per  default the  **options.CheckConsentNeeded**  is set to true. We have to remember, that by default Flashmessage uses the **CookieTempDataProvider** as ITempDataProvider (which uses cookies :)). 
When people do not accept the cookie consent (or you removed the cookieconsent partial), the consent is always checked, and since endusers never agreed to cookies, cookies are not used (thus IFlashmessage cannot store flashmessages accross webrequests, since cookies are "lost"), 

This leaves us with the following options:

- set options.CheckConsentNeeded to false (maybe only for certain requests, by checking the context parameter)
- use a different ITempDataProvider (see the documentation on them with all the pros and cons).

I hope this is helpful

**Comment by cakkermans** [comment]
@hypervtechnics I attempted to recreate your scenario using a double redirect where during each redirect a message is added. After these two redirects both messages are shown.

I am closing this issue for now. Please let me know if the issue persists.
